### ISSUE TITLE
SI B1 Model06 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-dipoles-b1#1]
Fieldmap for model without pole face strips:
 si-dipoles-b1/model-06/simulation/magnetic/2017-01-10_B1_Model06_Sim_X=-32_32mm_Z=-1000_1000mm_Imc=439A.txt

**Comment by xresende** [comment]
fmap analysed. integrated dipolar and quadrupolar fields are within specs. multipolar fields are off. DA calculations will be run to check relaxation on these.

**Comment by LuanaVilela** [comment]
Updated B1 model. New fieldmap:

 si-dipoles-b1/model-07/simulation/magnetic/2017-01-19_B1_Model07_Sim_X=-32_32mm_Z=-1000_1000mm_Imc=452.4A.txt

**Comment by xresende** [comment]
new fmap analyzed. beam dynamics calculation with multipolos of b1 and b2 being run...

**Comment by LuanaVilela** [comment]
Previous model was not approved due to decrease of dynamic aperture and beam lifetime. 
Added fieldmap for new model (Model 08):

si-dipoles-b1/model-08/simulation/magnetic/2017-02-01_B1_Model08_Sim_X=-32_32mm_Z=-1000_1000mm_Imc=451.8A.txt
